site_name: Helpfully
repo_name: BetterThanReal/Helpfully
repo_url: https://github.com/BetterThanReal/Helpfully

theme:
  name: material
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'
    scheme: preference

extra_css:
  - css/extra.css

nav:
  - Overview: index.md
  - Installation: installation.md
  - API Reference:
      - Overview: api-reference/index.md
      - debug: api-reference/debug.md
      - functions: api-reference/functions.md
      - Logger: api-reference/Logger.md
      - paths: api-reference/paths.md
      - tables: api-reference/tables.md
  - Source:
      - Changelog: changelog.md
      - License: license.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.superfences
